name: Attu Dev Release

on:
  pull_request_target:
    branches: [main]
    types: [closed]

concurrency:
  group: attu-dev-release-main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Docker Build and Push (Multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          tags: |
            zilliz/attu:dev
          cache-from: type=registry,ref=zilliz/attu:cache
          cache-to: type=inline
          build-args: |
            VERSION=dev
          push: true

  tag_issue:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Extract Issue Number from PR Body
        id: extract_issue
        env:
          PR_BODY: "${{ github.event.pull_request.body }}"
        run: |
          echo "ISSUE_NUMBER=$(echo "$PR_BODY" | grep -oP '(?<=#)\d+' | head -n 1)" >> $GITHUB_ENV

      - name: Add ready_to_release label to issue
        if: env.ISSUE_NUMBER != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          labels: ready_to_release
          number: ${{ env.ISSUE_NUMBER }}
